[project]
name = "busqueda"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Daniel Peña", email = "danielpenacruz@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.143.0",
    "httpx>=0.28.1",
    "uvicorn>=0.54.0",
]

[project.scripts]
busqueda = "busqueda:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"
